language: node_js
node_js:
- '6'
branches:
  only:
  - master
  - develop
  - /^v.*$/
before_script:
- npm install --quiet -g gulp
- npm install
before_deploy:
- npm run compile
deploy:
- provider: releases
  api_key:
    secure: CvSRQRmD0Rt/+TnPZ1aL8VDE0rBqMrSUv/d0svN43wKdcykg5aDEjrJN7AG9mjD9mJKL58ptRVJqUVPdC6Mkg18bbvphO3Mug0/Sxjn6/0H0x/Dmp4AMz2mtLzKkZsrlpxrQQjdGI2NZMzQ5ZfAoSA39ovfGzMP+wikVbrS2+qjFLlyg9iY89iHD1IgaZxZLnYZuV5HBTchWN7TkL9TncclU34vuWj/BF9yYl/SHxbGPtD7ZG1xmhOK1rART7lqFLEYgke0pjE6DkLrqLhS5gjSlwhx/fKbn6cWgOL6K8A5Jy66JWP66p5y4BoxHPXKK9k+DLATW7qe9d2L1/K8wvtALBtxVIjibQRRJreHjdhGfn3XCIWOGpvsYZ8a84vnTQcbmJJk9II0Bcajn5EAp3mqVH7MHgpc0XPA7azo7C04x2divZHeppO7U4bxFjx8IUGvyaRoS6ymYIQLeapX9OII6zZanmI64qAHkAcKH5IDvCjscDl3jrLMj/q0+bSSkHGarB5STN8PYeGirMVlqIDbExmbvs9STLZeKnq/kn6fPV5GJMNEm3KkyjyILeNQwD3WJfP4QPAMAtiAE0MGZ03PsxW8K73yHz8uaVkSONRDqIk0eFJUdZ49DwIomK42hkZf7QwNtHKm15UZlGCQVXMRdJXCEHdT5+PJzzzvY3yQ=
  file: dist.zip
  skip_cleanup: true
  on:
    tags: true
